name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Install missing libraries
        run: sudo apt-get install -y \
          libwoff1 \
          libopus0 \
          libwebp6 \
          libwebpdemux2 \
          libenchant1c2a \
          libgudev-1.0-0 \
          libsecret-1-0 \
          libhyphen0 \
          libgstreamer1.0-0 \
          libgstreamer-plugins-base1.0-0 \
          libvpx5 \
          libgtk-3-0 \
          libharfbuzz-icu0

      - name: Run tests
        run: npm run test
